# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec2920542eb97a9e7e004869ccc6fb4e81bfe026f2cd9c48de25850c72d41962530cbe0ed4947e338409ee26b68bc14db630250721e87e1450fd738b2390a133

test:
  secret_key_base: f5487d70a91e211cd97e9c2c8e901bc81ea1b021acf04bcc74dd1a5f2e39432eb9e808e6880d43d184ddb3a0bc179b2c960e8bbab4551c089e3895d7f34a0b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
